Project Development Phase/Sprint 4/accounts/urls.py
from django.urls import path
from.views import register_view, login_view, logout_view

app_name = "accounts"

urlpatterns = [
    path('register/', register_view, name = "register"),
    path('login/', login_view, name = "login"),
    path('logout/', logout_view, name = "logout"),

]

Project Development Phase/Sprint 4/app/urls.py
from django.urls import path
from .views import home_view, extract_view, result_view

app_name = "app"

urlpatterns = [
    path('', home_view, name="home-view"),
    path('extract/', extract_view, name="extract-view"),
    path('result/<str:value>/<str:accuracy>/', result_view, name="result-view"),
]

Project Development Phase/Sprint 4/hdr/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
#helo


urlpatterns = [
    path('', include("app.urls")),
    path('admin/', admin.site.urls), 
    path('accounts/', include("accounts.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project Development Phase/Sprint 4/accounts/models.py
from django.db import models

# Create your models here.

Project Development Phase/Sprint 4/app/models.py
from django.db import models

# Create your models here.

Project Development Phase/Sprint 4/accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms

User = get_user_model()

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=255, widget=forms.TextInput( attrs={
                "class": "form-control"
    }))
    email = forms.EmailField(max_length=255, widget=forms.TextInput( attrs={
                "class": "form-control"
    })
    )
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "user-password"
    }))
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "user-confirm-password"
    }))

    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username__iexact=username)

        if qs.exists():
            raise forms.ValidationError("This is an invalid username, please pick another")

        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        qs = User.objects.filter(email__iexact=email)

        if qs.exists():
            raise forms.ValidationError("This email is already in use")

        return email
        



class LoginForm(forms.Form):
    username = forms.CharField(label="",widget=forms.TextInput( attrs={
                "placeholder": "Enter Username",
                "class": "form-control"
    }))
    password = forms.CharField(label="",
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter Password",
                "class": "form-control mt-4",
                "id": "user-password"
    }))

    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username__iexact=username)

        if not qs.exists():
            raise forms.ValidationError("This is an invalid user")

        return username

Project Development Phase/Sprint 4/app/forms.py
from django import forms



class PhotoForm(forms.Form):
    photo = forms.FileField(label="",required=True, 
                        widget=forms.FileInput(
                            attrs={
                                "name":"photo",
                                "type":"file",
                                "class": "form-control",
                                "id":"inputGroupFile04",
                                "aria-describedby":"inputGroupFileAddon04",
                                "aria-label":"Upload",
                            }))

Project Development Phase/Sprint 4/accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.urls import reverse

from .forms import LoginForm, RegisterForm


User = get_user_model()

# Create your views here.
def register_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")
        try:
            user = User.objects.create_user(username, email, password)
        except:
            user = None
        if user != None:
            return HttpResponseRedirect(reverse('accounts:login'))
    context = {
        "form": form
    }
    return render(request, "accounts/registration.html", context)

def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(request, username=username, password=password)
        if user != None:
            login(request, user)
            return HttpResponseRedirect(reverse('app:home-view'))
    context = {
        "form": form
    }
    return render(request, "accounts/login.html", context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))

Project Development Phase/Sprint 4/app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import PhotoForm
from .recognizer import recognize
from django.contrib.auth.decorators import login_required

# Create your views here.

def home_view(request, *args, **kwargs):
    context = {}
    return render(request, "app/home.html", context)

@login_required
def extract_view(request, *args, **kwargs):
    my_form = PhotoForm()
    context = {
        "form": my_form,
    }
    if request.method =="GET":
        pred = ()

    if request.method == "POST":
        img = request.FILES.get('photo')
        pred, others, img_name = recognize(img)
        return HttpResponseRedirect(reverse("app:result-view", kwargs={"value": str(pred[0]), "accuracy": str(pred[1])}))
        # 

    return render(request, "app/extract.html", context)

@login_required
def result_view(request, *args, **kwargs):
    print(request.path)
    var = request.path
    l = var.split("/")
    print(l)
    value = l[2]
    accuracy = l[3]
    return render(request, "app/result.html", { "val": value, "acc": accuracy})

Project Development Phase/Sprint 4/templates/accounts/login.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}
<div class="container ml-auto col-md-3 mt-5">
    <div class="card shadow-lg p-3 mb-5 bg-body rounded p-3">
        <div class="text-center mx-5 my-2">
            <h3>Enter Credentials to Login</h3>
        </div>
        <form method="POST">
            {% csrf_token %}
            {{ form.username|as_crispy_field }}
            {{ form.password|as_crispy_field }}
            <div class="text-end">
                <button class="btn btn-success mt-3" type="submit">Signin</button>
            </div>
        </form>
        <div class="text-end">
            <p class="mt-2">
                Don't have an account?
                <a href="{% url 'accounts:register' %}">signup</a>
            </p>
        </div>
    </div>
</div>
{% endblock content %}

Project Development Phase/Sprint 4/templates/accounts/registration.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}

<div class="container ml-auto col-md-3 mt-5">
    <div class="card shadow-lg p-3 mb-5 bg-body rounded p-3">
        <div class="text-center mx-5 my-2">
            <h3>Enter Credentials to Signup</h3>
        </div>
        <form method="POST">
            {% csrf_token %}
            {{ form.username|as_crispy_field }}
            {{ form.email|as_crispy_field }}
            {{ form.password1|as_crispy_field }}
            {{ form.password2|as_crispy_field }}
            <div class="float-end mt-3">
                <button class="btn btn-success" type="submit">Signup</button>
            </div>
        </form>
    <div class="text-end mt-3">
        <p>
            Already have an account? <a href="{% url 'accounts:login' %}">Signin</a>
        </p>
    </div>
</div>
</div>
{% endblock content %}

Project Development Phase/Sprint 4/templates/app/extract.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% comment %} <div class="container text-center" style="padding: 100px; padding-bottom: 0px margin-top: 230px; margin-bottom: 0px justify-content: center; align-items: center; width: 800px; height: 400px;"> {% endcomment %}
<div class="container col-md-3 text-center" style="align-items: center; justify-content: center; ">
    {% comment %} <h1 class="my-5" style="font-size: 3em;">Upload an image to Convert !!!</h1>
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
        <div class="input-group">
            <input type="file" class="form-control" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
            <button class="btn btn-outline-secondary" type="submit" id="inputGroupFileAddon04">Button</button>
        </div>
    </form> {% endcomment %}
    
    <h1 class="my-5" style="font-size: 3em;">Upload an image to Convert !!!</h1>
    <form action="./" method="POST" enctype="multipart/form-data" class="row row-cols-lg-auto align-items-center"> {% csrf_token %}
            {{ form.photo.label_tag }}
            {{ form.photo|as_crispy_field }}
            <button type="submit" class="btn btn-primary">Recognize</button>
    </form>


</div>
{% endblock content %}

Project Development Phase/Sprint 4/templates/app/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center" style=" display: flex; justify-content: center; align-items: center; width: 1920px; height: 650px;">
    <h1 style="font-size: 4em;">A Novel Method for Handwritten Digit Recognition System</h1>
</div>

{% endblock content %}

Project Development Phase/Sprint 4/templates/app/result.html
{% extends 'base.html' %}
{% block content %}
<div class="my-5 container col-md-3 text-center" style="align-items: center; justify-content: center; ">
    <h1>Value: {{ val }}</h1>
    <h1>Accuracy: {{ acc }}</h1>
    <a href="{% url 'app:extract-view' %}"><button class="btn btn-primary mt-3">Back</button></a>
</div>
{% endblock content %}

Project Development Phase/Sprint 4/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Handwritten Digit Recognition</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <style>
      body {
        background-image: {% static 'static/wall.gif' %};
      }
    </style>
  </head>
  <body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    {% include 'navbar.html' %}
    {% block content %}

    
    {% endblock content %}
  </body>
</html>

Project Development Phase/Sprint 4/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-brand text-decoration-none pe-none">
            <a class="text-decoration-none pe-none user-select-none fs-3 fw-bold" style="color: #00276b">IBM</a>
        </div>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'app:home-view' %}">Home</a>
                    
                </li>
            </ul>
            <div class="d-flex">
                {% if request.user.is_authenticated %}
                <div class="float-start">
                    <a href="{% url 'app:extract-view' %}">
                        <button class="btn btn-outline-success me-2" type="submit" to="">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
                                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
                              </svg>
                            Extract
                        </button>
                    </a>
                </div>
                <a href="{% url 'accounts:logout' %}"><button class="btn btn-warning me-2" type="submit">
                    Signout
                </button></a>
                {% endif %}
                {% if not request.user.is_authenticated %}
                <a href="{% url 'accounts:login' %}">
                <button class="btn btn-info me-2" type="submit">Signin</button></a>
                <a href="{% url 'accounts:register' %}">
                <button class="btn btn-info me-2" type="submit" to="">Signup</button></a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>